travis:
  secure:
    BINSTAR_TOKEN: t6Nsl9idjMs2yl51FNoMm/mNPOnVfBwdgmrpifo3oMzexFRoltsZB7SIruYc9QFHaa4HabGAM71AvP9htuz6N2ydBD+DSZtCkPAylKFZIs+bVm3vO/KbIJzQRDEGNEVBRfMeMIOprisDbQqCx2ZXi1THqBKzIRq3rZa7fnfJZ+eo8kUuDhBrX3M3jX1HFiS2aWRKViYhVKjLXxs5c3nmu0By/CeBf1EU+QUZe3Ciz4Q+JSuxvwaDVAFXjW828b+1icnUTQDtWYiGUpS9nd/qxAv9AeFTUpQXyiwC2+WlGRDCFegpw6UV8RbymgKAXwLyLSICpAM+qP2xpMMUSu5VMJtDN7q292yQqcjGhwnQCQDtneOnLT4XxeK2rTvq9zGwn8bV4/NOVuhdYTKPFi7dWK7KW7z0wwdR0bx8to7IbC5Gsam7a16VORYCeUJc3Pu1kwTD7appc1ct07Rz4hBIZbZwfRi1cfoH05ayhmii/s3XoxNkOiDQOP4nhVFpvNRqaA8JQjg24Wz9SrH8g0fp4g5d2tSNSLBwvL68KCmtL8odMV5LgiGoQf2NSMTe1hsQXNN4dbZ1d+MDUCpCqxbaPNF7gyHvb3XFRqXXtvKuA+uAqq2EdZt9zPxMtJXtaBiy7vtJjgEYxss5rdkWrRE6dy9J+NhFGz84HOamsN7kb5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
